name: Node.js Backend CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: backend/package-lock.json
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: latest
          mongodb-db: shoppingDB
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        env:
          DB_LOCAL_URI: mongodb://localhost/shoppingDB
          ENV: DEV
  deploy:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v0'
      with:
        working_directory: backend
    - id: 'Print url'
      run: 'echo "${{ steps.deploy.outputs.url }}"'